# Generated by Django 4.1.7 on 2023-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="country_of_origin",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("France", "France"),
                    ("Italy", "Italy"),
                    ("Germany", "Germany"),
                    ("Netherlands", "Netherlands"),
                ],
                default="Unknown",
                max_length=25,
            ),
        ),
    ]
